### ISSUE TITLE
kasmweb

### ISSUE THREAD

**Issue by eric23xa** [gitpod-io/workspace-images#1068]
Hello, I have a problem with  installing kasmweb
Every time I install kasmweb  from any source I get the following problem >>> 
Loaded image: kasmweb/terminal:1.12.0
Initializing Database
Setting Seed file as /opt/kasm/1.12.0/conf/database/seed_data/default_properties.yaml
yaml: unmarshal errors:
  line 26: mapping key "restart" already defined at line 6
  line 43: mapping key "restart" already defined at line 38
kasm_db_1.12.0
yaml: unmarshal errors:
  line 26: mapping key "restart" already defined at line 6
  line 43: mapping key "restart" already defined at line 38
01:41 AM
For my information, I have modified the file hundreds of times and the problem has not been resolved
where 
Minimum Version Requirements
docker > 18.06
docker compose > 2.1.1
As mentioned in the official official website : https://kasmweb.com/docs/latest/install/system_requirements.html#operating-system
I also know that on one occasion I did the installation and by chance the copy worked without a problem, but I do not know the reason because at that time I deleted the operating system.
I've even tried changing the operating system from ubuntu 20.04 to Debian but also not work  
I think the problem is in the latest version of the kasmweb system 
I have heard about Gitpod will upgrade the default workspace images to utilize the latest Long Term Support (LTS) ....
So I hope to solve the problem with the upgrade and the new update 
thank you

**Comment by Derroylo** [comment]
@eric23xa for what would you need kasm in gitpod? Same as in your other issue, please use the code tags and provide a full example so it can be repeated. Also the error message usually means your yaml files are not formatted correctly, so i think it has nothing todo with the gitpod workspace image.

**Comment by Derroylo** [comment]
@eric23xa 
`Secondly, I am talking about real problems. If there was no problem, I would not have spoken`
Where did i say that it is not a real problem? I only said that the problem might not be related to gitpod itself, as you confirmed, it is a problem with kasm.

`And I do not like anyone telling me not to do this or that because I have paid from my pocket to your platform and I'm good with out you .`
First of all, i am not in any form related to gitpod, just wanted to help with your problem. Second, i never said you should not use it, i just asked out of curiousity why you need/want to use kasm in gitpod. Just a harmless question, nothing more. It was also not offtopic, as gitpod has also an option for VNC, which might have been an alternative for you, if you develop desktop applications.

`You do not make the inability to answer the problem drift into a non-topic or deny it in the first place.`
I didn´t deny that the problem exists, where do you read that from? I only said, it might not be a problem with gitpod itself and more of a problem with kasm.

**Comment by eric23xa** [comment]
@eric23xa
First of all, i am not in any form related to gitpod, just wanted to help with your problem......etc
***********************
since it's you (not in any form related to gitpod.....) so I said from the beginning First of all, I do not know if this place belonged to the gitpod.io platform or not
all this does not concern you,I am only annoyed by the limitations and problems of the platform, and when I contact support on a specific problem, there The response is delayed and there is no solution.
ok I thank you for your response.
