### ISSUE TITLE
Don't use Pyenv

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/workspace-images#136]
Python via Pyenv breaks a lot of integrations, and I would really like it wasn't the default way of doing 3.x.

Proposed solution:
* ~~Keep Pyenv installed~~
* Keep 2.x as is
* ~~Change the *system's version of python3* to 3.8.0~~
* Source build our python

**Comment by jankeromnes** [comment]
Hey @RDIL, thanks again for this proposal! We don't have much experience with Python dev environments, so any insights are very welcome.

> Python via Pyenv breaks a lot of integrations, and I would really like it wasn't the default way of doing 3.x.

Could you please specify which integrations are broken by Pyenv?

> Change the _system's version of python3_ to 3.8.0

I think we've just (accidentally) done that by upgrading to Ubuntu 20.04, which seems to ship with Python 3.8 by default.

Actually this even broke some Gitpod workspaces (specifically, some of the Python VS Code extensions -- e.g. I think Pylint) because they seem to favour the latest available version.

So I'll upgrade Python to 3.8.2 now (if that still breaks TensorFlow, we can ping a lower version in TensorFlow workspaces, that's pretty easy now), and also 2.7.18 since that's out.

I'm still interested in your thoughts on using system Python instead of Pyenv (or maybe one day removing Pyenv entirely), but I think we'll need to do a lot of testing, and ensure that important things continue to work as before (i.e. Gitpod's Python VS Code extensions; persistence of `pip install` packages under `/workspace`; etc; etc).

**Comment by RDIL** [comment]
Hey @jankeromnes,

1. Lots of things are effected by Pyenv, from shims not being equipped in raw shells that are not bash (eg https://github.com/pawamoy/mkdocstrings/issues/91), and in addition, because with Pyenv we are technically always in a virtualenv, it breaks some tools that expect to be in a global install.

2. I think its not great that some workspaces broke, but I also think that if they want tools they should be able to install them by themselves, because most projects are only 1 language and this image contains more than 8.  The idea should be that this image provides the base, and can be extended upon.

3. I think if anything not using pyenv will fix things instead of break them.  Plus, Python isn't as much of a language like ruby which can depend on certain versions down to the git commit ID, it generally works as long as the release is from the last year, but gets benefited the newer it is.  

While the system does now have python, it is prebuilt.  What I did for [better-wsfull](https://github.com/RDIL/better-wsfull) (my own image) was build it from source, to get certain features like LTO and ipv6 support.

**Comment by princerachit** [comment]
I am closing this issue as there has not been much traction since ~2 years now.
