### ISSUE TITLE
Postgres images: persist data after workspace stop

### ISSUE THREAD

**Issue by marcopeg** [gitpod-io/workspace-images#171]
Hello, I'm running the postgres image and all works fine until I stop/start the workspace and all the data are lost.

I read that data under `/workspace` are persisted, but I can't find a way to move the postgres data folder in there when extending the Dockefile:  
https://github.com/marcopeg/hasura-gitpod/blob/master/.gitpod.Dockerfile

Can you help?

**Comment by jankeromnes** [comment]
Hi @marcopeg, many thanks for reporting this issue!

Thanks to @jjangga0214, this problem was fixed in https://github.com/gitpod-io/workspace-images/pull/172 and an updated `gitpod/workspace-postgresql` default image will be available on Docker Hub and in Gitpod shortly (ETA about ~1 hour).

We've changed the default location for PostgreSQL data to `/workspace/.pgsql/data`, which would solve your issue without requiring any change.

(Still, if you desire to change the location, `$PGDATA` is now configurable via https://gitpod.io/environment-variables/, but in your case that's no longer necessary.)
