### ISSUE TITLE
Upgrade from Ubuntu Disco 19.04 (end-of-life) to Ubuntu Eoan 19.10 or Ubuntu Focal 20.04 LTS

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/workspace-images#196]
Ubuntu Disco reached end-of-life almost 3 months ago, on January 23rd: https://wiki.ubuntu.com/Releases

We should upgrade to a more recent version, ideally an LTS. In the future, let's not upgrade to non-LTS versions, because they reach end-of-life too quickly, while we want to minimize dependency churn and disruptions to Gitpod developers.

**Comment by jankeromnes** [comment]
This just became urgent, because all `apt-get` packages for Disco got removed from http://archive.ubuntu.com/ubuntu/dists/ yesterday.

Many thanks to @lechien73 for catching this in https://github.com/gitpod-io/gitpod/issues/1398

**Comment by Utopiah** [comment]
Has this been fixed? I just tried https://www.gitpod.io/docs/languages/r/ which relies on `FROM gitpod/workspace-full` itself still seems to be on 19.04

For people familiar with Docker/Ubuntu/Gitpod/Github that's trivial to fix but for newcomers it feels like a long way down to understand why some of their packages can't get installed.

**Comment by lechien73** [comment]
@Utopiah - are you sure? `FROM gitpod/workspace-full` builds from here: https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile, which is using `FROM buildpack-deps:focal` - Ubuntu 20.04 LTS.

Does running `lsb_release -r` from the terminal give you 19.04?

<img width="181" alt="Screenshot 2021-09-16 at 16 02 31" src="https://user-images.githubusercontent.com/21156053/133636405-cada2e52-bcc3-4645-8e05-dd49f176f5c2.png">

**Comment by Utopiah** [comment]
I did use lsb_release to check and it was 19.04, found out via 404 on apt update.

I tried `FROM gitpod/workspace-full:latest` giving me https://olive-wolf-3wod6krn.ws-eu16.gitpod.io/ as workspace but same 19.04.

**Comment by jankeromnes** [comment]
Hi @Utopiah! Oh, good catch. I think the reason is that in Gitpod's [R example repository](https://github.com/gitpod-io/Gitpod-R), the [.gitpod.Dockerfile](https://github.com/gitpod-io/Gitpod-R/blob/master/.gitpod.Dockerfile) hasn't been modified in 2 years.

Gitpod (currently) caches custom workspace images based on a hash of the custom Dockerfile. So, if the Dockerfile isn't modified in 2 years, the workspace image will be 2 years old, even for brand new workspaces 😕 (which I agree is bad and surprising).

The workaround is to force a rebuild of the workspace image, e.g. by:
- Committing a change to the custom Dockerfile (any change)
- Forking the example repository (Gitpod will see the custom Dockerfile as new in a new repository)

**Comment by Utopiah** [comment]
Thanks for the clarification @jankeromnes and I indeed suspected some form of caching but that's mostly because I understand a bit about container layer during their build process. I think for newcomers this can be tricky. I see similar problems with nvm or Dockerfile in general when relying on LTS and assuming that because containers or virtual environment are used, everything will "just work". Yet, when the process is done dynamically by applying updates or relying on pieces of software that are not pinned, even one small library that decided, and rightfully so IMHO, to stop supporting  what is older than LTS, things break.

 I don't have a suggestion beside insuring that at least what is destined to newcomers is indeed reflecting best practices so that they don't give up assuming that the problem is from their end.
