### ISSUE TITLE
Install Hub

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/workspace-images#238]
Let's consider adding Hub to our base image. See #186 and #76. CC @RDIL and @jankeromnes.

## Benefits
  - it offers `hub pull-request` which allows users to make PRs from CLI

## Downsides
  - Possible image size increases
  - UX: Not automatically logged in like `git` as of right now (this can probably be fixed)

**Comment by nicolo-ribaudo** [comment]
I propose to use `gh` instead of `hub`, which is the official CLI tool for GitHub (https://github.com/cli/cli).

**Comment by jankeromnes** [comment]
If `hub` is ever installed, we should also pre-authenticate it (which is tricky), otherwise you can't do anything interesting with `hub`, making having it a bit pointless.

See also:
- https://github.com/gitpod-io/workspace-images/issues/77#issuecomment-476185195
- https://github.com/gitpod-io/workspace-images/pull/186#discussion_r398400888

**Comment by sr229** [comment]
We should just use [gh](https://github.com/cli/cli) as @nicolo-ribaudo suggested, since we're more focused with the GitHub ecosystem.

**Comment by JesterOrNot** [comment]
Either way, we need to pre-authenticate @jankeromnes how is this implemented in Gitpod?

**Comment by sr229** [comment]
From what I can pull, since we authorize via OAuth2.0, they probably pulled our user token for it.

**Comment by geropl** [comment]
> they probably pulled our user token for it.

Yes. Does `gh` have to option to re-use git credential helpers?

**Comment by princerachit** [comment]
This issue is very old and not recent traction. Closing this.
