### ISSUE TITLE
Install ZSH

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/workspace-images#239]
Let's consider installing ZSH to Gitpod. See #186 and #76. CC @jankeromnes and @RDIL.

## Benefits

  - New Shell more people can easily use their favorite shell
  - Easily Run ZSH scripts in Gitpod without custom Dockerfile
  - According to @jankeromnes, ZSH feels fast with Gitpod

## Drawbacks

  - Possibly large size increases.

**Comment by RDIL** [comment]
I feel like https://github.com/gitpod-io/gitpod/issues/1555 would need to be fixed first.

**Comment by JesterOrNot** [comment]
Why AFAIK ZSH uses ~/.zshrc not ~/.bashrc.

**Comment by RDIL** [comment]
Yup but I think we should get the main shell working before adding a new one.

**Comment by sr229** [comment]
I don't see any benefits using ZSH. Gitpod is supposed to be a environment that just works. I don't want to additionally setup the shell if it doesn't work. `bash` should be enough for a lot of use cases, having your own custom shell should just be an afterthought.

**Comment by gengjiawen** [comment]
I like this idea, probably need add fish shell too. Though Shell is very personal. But developer like to use there own. I install fish in every of my env. So this is worth it.

**Comment by jankeromnes** [comment]
I also really like this idea!

But a prerequisite is to refactor all customizations of `.bashrc` into something more generic like a `.profile` (and then be sure to explicitly call `.profile` from `.bashrc` + `.zshrc` + `.fishrc` -- last time I checked `.profile` was not automatically executed by Bash).

Then there are probably many third-party images out there that also customize `.bashrc`. I don't think we can do anything about these (except send out a few PRs when we spot occurrences), so I think the third-party image authors would be responsible for implementing ZSH / Fish support. We can provide helpful guides for that in the Gitpod docs and/or https://community.gitpod.io

Any volunteers to start a PR? 🙂

**Comment by gengjiawen** [comment]
Any timeline this available in production ?

**Comment by RDIL** [comment]
@gengjiawen any new workspaces created after the merge of this PR should have it.

**Comment by jankeromnes** [comment]
@gengjiawen Seems like the CircleCI run of https://github.com/gitpod-io/workspace-images/commit/0d86f18fcb06832838d2cb77636d2c1a6a7dbe6c was 100% successful:

<img width="1230" alt="Screenshot 2021-03-09 at 13 41 34" src="https://user-images.githubusercontent.com/599268/110472115-404f5200-80dd-11eb-97e5-da60183d46af.png">

So Docker Hub should already have `zsh` and `fish` pre-installed in `gitpod/workspace-full` & co. Are you using a custom Dockerfile? (If so, please commit any character change in it to update. -- If not, we might have a bug in Gitpod where a new `gitpod/workspace-full` is not pulled if an older one is already available.)

**Comment by gengjiawen** [comment]
Is `gitpod/workspace-full` default image for gitpods (looks like there is base image)? I am trying [trending repo](https://github.com/trending) to avoid image cache. But fish and ninja not looks installed.
![image](https://user-images.githubusercontent.com/3759816/110478421-4ebe5d80-811f-11eb-8587-cd68fd568d3e.png)

**Comment by jankeromnes** [comment]
> Is gitpod/workspace-full default image for gitpods (looks like there is base image)?

Yes, `gitpod/workspace-full` is the default image for Gitpod workspaces (when projects don't specify a custom image or Dockerfile).

`gitpod/workspace-base` is a recent refactor, which created an "empty" image without any language stack from `-full`. I don't think we use it anywhere yet (except to build `-full` on top of it), but it could be useful if you want to produce a small custom image with just the tools you want and nothing else.

> I am trying trending repo to avoid image cache. But fish and ninja not looks installed.

Aha, thanks for trying. This may confirm a suspicion we had that Gitpod's `image-builder` pulls `gitpod/workspace-full` only the first time, and then always re-use it (even if a newer version is available in Docker Hub).

The fix for this would be to make sure Gitpod always checks for newer versions of `gitpod/workspace-full` before creating workspaces (drawback: The first person to use each newer version will have to wait for the pull.)

Potential workarounds:
- I believe restarting the `image-builder` pod in your gitpod.io cluster will force a new pull
- You could use a more specific tag to specify which version of `gitpod/workspace-full` you want (for example, every new release is tagged `:latest`, but also `:commit-XYZ` where `XYZ` is the commit SHA -- e.g. the current latest release is `gitpod/workspace-full:commit-0d86f18fcb06832838d2cb77636d2c1a6a7dbe6c`)

**Comment by csweichel** [comment]
@jankeromnes you are correct. image-builder resolves `gitpod/workspace-full:latest` once after startup and caches this value until it is restarted.

**Comment by gengjiawen** [comment]
Thanks for the detailed reply. 

> I believe restarting the image-builder pod in your gitpod.io cluster will force a new pull

where is specific location ? I can't find this in settings.

**Comment by jankeromnes** [comment]
> > I believe restarting the image-builder pod in your gitpod.io cluster will force a new pull
> 
> where is specific location ? I can't find this in settings.

Sorry, that was a bit ambiguous. This is only something a Gitpod ops/admin person can do, and might have undesirable consequences (e.g. need to watch for ongoing Docker builds that should not be interrupted, might cause pull slowness for everyone in that regions, etc) -- so the other proposed workaround is probably better.

For what it's worth, you can see which Gitpod cluster you're in by looking at your workspace URLs (there will be something like `ws-eu03` or `ws-us02` in the domain).

**Comment by gengjiawen** [comment]
> This is only something a Gitpod ops/admin person can do

Is it an option to enable normal user to force refresh base image ？ I am still not getting the latest image.

**Comment by gengjiawen** [comment]
Give it a second test, fish and zsh in base image, not in full.
Is it because current CI not building base image first ?
