### ISSUE TITLE
Wrong version of NPM installed; breaking prebuilds

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/workspace-images#358]
The script installs Node 14.x, which goes with NPM 6.x. But for some reason, NPM 7.x is being packaged instead. NPM 7.x represents major breaking changes, especially with `npx`. Can it please use the proper version of NPM. I'm not sure where the 7.x is coming from.

**Comment by smacintyre** [comment]
This seems related to the bump to Node v14.15.5 -- which seems to come with NPM 7.x; while both v14.15.4 and the current LTS, v14.16.0 both come with NPM 6.x.

I see the build has been been automatically bumped to 14.16.0 -- how can we start using that version?

**Comment by jankeromnes** [comment]
Hi @smacintyre, good catch! Thanks for reporting this.

The Node.js version in `gitpod/workspace-full` has indeed been bumped to v14.16.0 recently: https://github.com/gitpod-io/workspace-images/commit/216a1b74295dbdf581054ebe3393e2703eac88e6

We're planning to built & deploy a new batch of Gitpod workspace images including this change in the coming days (right after https://github.com/gitpod-io/workspace-images/pull/354 is fully tested and merged), which will automatically give you Node.js v14.16.0 in Gitpod if you're using the default image `gitpod/workspace-full` or a custom image based on that.

On a side note, you can also opt to pin your own specific Node.js version in your project's `.gitpod.Dockerfile`, e.g. like so:
- https://github.com/gitpod-io/workspace-images/pull/178#issuecomment-602465333
- https://github.com/eclipse-theia/theia/blob/1ff2d0c2b32f8d5e2079a8c437ffb17ec148ee67/.gitpod.dockerfile#L16-L22

**Comment by smacintyre** [comment]
Hi @jankeromnes thank you for your reply. 

I already applied that workaround. The bigger question is why the wrong version of npm was installed. According to the [release notes for Node v14.15.5](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.15.5), it's packaged with npm v6.14.11. If you do a `nvm uninstall v14.15.5` and then  `nvm install v14.15.5`, the correct version of npm installed. So maybe it was just an issue with the build. Maybe you could just rebuild the current release to fix it? That would help others experiencing the same issue.

**Comment by jankeromnes** [comment]
Glad that you already had it solved! And good call, maybe this was a temporary NVM/Node.js build problem when we built the previous batch of Gitpod workspace images, and a simple rebuild would resolve it.

However, we're trying not to publish different versions of `gitpod/workspace-full` too frequently (because the image is somewhat large, and having too many different versions of it causes some ops stress on Gitpod's servers, e.g. making workspace starts slower, filling up disks faster, etc), so I think we'll count on the next full release to resolve this.

FYI, the next build of `gitpod/workspace-full` and its derived images will include the following changes (plus any changes we merge now prior to the release):

https://github.com/gitpod-io/workspace-images/compare/e3aaa3f778f068862d4706ac321d6fc776d2ba7d...master

**Comment by smacintyre** [comment]
Thank you!
