### ISSUE TITLE
Use system Python for internal purposes

### ISSUE THREAD

**Issue by orucky** [gitpod-io/workspace-images#38]
As @AlexTugarev explained to me, we use both Python 2.7 (in some Node.js scripts) and Python 3.6 (for the language server). We install (currently 3.6.6) explicitly using `pyenv` version switcher.

In `buildpack-deps:cosmic` we currently base on, there's (currently) Python 2.7.15+ and Python 3.6.7 bundled. Therefore I suggest keeping `pyenv` in place (so that our users have freedom to download & use different versions), but not preinstall 3.6.6 and set is as default for 3.x - because we don't need it and as we base on a live distribution, the preinstalled version will probably get updated sooner than the explicit version we define anyway.

**Comment by AlexTugarev** [comment]
What are the "internal purposes"? 

> not preinstall 3.6.6 and set is as default for 3.x - because we don't need it and as we base on a live distribution, the preinstalled version will probably get updated sooner than the explicit version we define anyway.

I disagree. The Python LS (or rather `jedi`) is not working nicely with the latest versions of Python, which means it needs to be tested with newer versions. E.g. 3.7 would be really nice, but unfortunately it's still [not playing nice](https://github.com/davidhalter/jedi/issues). And as soon as this those issues are sorted out, I'd like to bump the version. That's the reason to control the installation.

**Comment by jankeromnes** [comment]
What bothers me is that by default, `python` resolves to `python3.6` in Gitpod workspaces. In any other environment that I know of, `python` resolves to `python2.7` by default (even when Python 3 is installed). This causes a few issues when projects use `python` while expecting it to be `python2.7`.

This was introduced by the command `pyenv global 3.6.6` in https://github.com/gitpod-io/workspace-images/commit/401306f8cd70ef02594deb7781a23eccc9332d8f. @svenefftinge, do you remember why you needed to switch the global Python from 2 to 3?

Note: [This article](https://hackernoon.com/reaching-python-development-nirvana-bb5692adf30c) says that you can also use `pyenv local 3.7.0` to only change the Python version in a specific directory. This seems like a better idea.

**Comment by jankeromnes** [comment]
Follow-up: A fix I found for one of these Python 2/3 mixups was to do `pyenv local system` in the directory where the failing commands were run.

However, maybe we'll want to remove the `pyenv global 3.6.6` (leaving the `system` default everywhere), and just do a `pyenv local 3.6.6` at the precise location(s) where we actually need 3.6.6?

**Comment by jankeromnes** [comment]
@AlexTugarev do you think we could remove this line?

https://github.com/gitpod-io/workspace-images/blob/4482866443f354eb8ff4edbfe55feb1c484d6b79/full/Dockerfile#L135

This would leave `python` bound to `python2.7` system-wide in all workspaces (that's what most projects expect), and we can still use `pyenv local 3.6.6` in the places where we do actually need `python` to be `python3.6`.

**Comment by AlexTugarev** [comment]
@jankeromnes, that `pyenv` installation is not (just) about having `python` installed in a certain  version. 

The global version is set to `3.6.6` as this is the latest version supported by the `pyls` (at least it was at the time we've added it.) As of now, we do rely on the python version which is installed globally, and we even pre-install the `pyls` package in the very next step: 
https://github.com/gitpod-io/workspace-images/blob/4482866443f354eb8ff4edbfe55feb1c484d6b79/full/Dockerfile#L136

Currently, when you open a python file in the editor the LS will be started using the global `python3` and it will use all modules installed there.

This was our initial goal to synchronize the python used in the terminal with the version in the editor. In the next step we should definitely make this configurable. We've discussed some options in Theia already, cf. https://github.com/theia-ide/theia/issues/2973, and a major blocker war just resolved recently, which is to pass options from Theia frontend to the language server contribution on the backend. This should allow us to select the Python version in the editor.

That's why we rely on the the global `python3` installation, but if there is a way to stop pyenv from hijacking `python`, that would be awesome, right?

**Comment by jankeromnes** [comment]
Interesting. Then I guess the only purpose of `pyenv global 3.6.6` is to redirect the `python3` shim from `/usr/bin/python3` (`3.6.7`) to `/home/gitpod/.pyenv/shims/python3` (`3.6.6`).

But it has the unfortunate side-effect of also redirecting the global `python` shim from `2.7.15+` (system) to `3.6.6`:

```
$ echo "python: $(python --version), python2: $(python2 --version), python3: $(python3 --version)"
python: Python 2.7.15+, python2: Python 2.7.15+, python3: Python 3.6.7
$ pyenv global 3.6.6
$ echo "python: $(python --version), python2: $(python2 --version), python3: $(python3 --version)"
python: Python 3.6.6, python2: Python 2.7.15+, python3: Python 3.6.6
```

Potential improvements here:
- Try to remove `pyenv global 3.6.6`, and see if `pyls` works again with `python3 = 3.6.7`
- Uninstall the system's `/usr/bin/python3`, so that `pyenv install 3.6.6` already sets up `python3` as `3.6.6` without needing `pyenv global 3.6.6`
- Find another way to make `/home/gitpod/.pyenv/shims/python3` point to `3.6.6` without impacting the global `python` shim

**Comment by AlexTugarev** [comment]
### ```bash
➜  ~ pyenv global 2.7 3.6.6
➜  ~ pyenv versions
  system
* 2.7 (set by /Users/tugarev/.pyenv/version)
* 3.6.6 (set by /Users/tugarev/.pyenv/version)
➜  ~ python --version
Python 2.7
➜  ~ python3 --version
Python 3.6.6
```

@jankeromnes, WDYT of this?

or is it a requirement to use the `system` version?

**Comment by jankeromnes** [comment]
Oh wow, great find! I tried `pyenv global system 3.6.6`, which seemed to "ignore" `3.6.6`, but your solution works!

Now we can try reverting the global `python` from `3.6.6` to `2.7`. Hopefully projects haven't begun to rely on that strange state of things.

Also, should we test `pyls` with latest `python3` again? (i.e. `3.6.7`)

**Comment by AlexTugarev** [comment]
> Also, should we test `pyls` with latest `python3` again? (i.e. `3.6.7`)

we've set a fixed version for pyls, as a newer version had a breaking change. well that change only breaks in our deployment scenario and we should fix it. then we can update. even to 3.7, cf. https://github.com/davidhalter/jedi/commit/1cf5b194caaaef5c61bf83b8ba76d0d9ca29beb2

**Comment by AlexTugarev** [comment]
@jankeromnes please reopen, if you think there is any action required.
