### ISSUE TITLE
rustup update not working

### ISSUE THREAD

**Issue by extrawurst** [gitpod-io/workspace-images#464]
@aledbf you asked me to open a separate issue for this, so here we go:

```
gitpod /workspace/XXX $ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)

gitpod /workspace/XXX $ rustup update
info: no updatable toolchains installed
error: rustup is not installed at '/workspace/.cargo'
```

currently the container has an older version of rust installed and so I thought the regular workflow to update rust inside my gitpod would work, but it does not.

**Comment by corrieriluca** [comment]
Hi, I figured out that in the `full` Docker image, the `CARGO_HOME` environment variable is set to a custom value:

https://github.com/gitpod-io/workspace-images/blob/b338bce383efc89dd31b12c18110b7c88fe75f53/full/Dockerfile#L197-L198

When running `rustup` this causes the error `rustup is not installed at '/workspace/.cargo'` because it does not find `rustup` in the `CARGO_HOME` directory (here `/workspace/.cargo`).

The temporary solution I found is simply `unset CARGO_HOME` while doing `rustup update` and optionally set it to `/workspace/.cargo` back again if you want.
