### ISSUE TITLE
current vscode-go requires extra tool dlv-dap to function

### ISSUE THREAD

**Issue by trashhalo** [gitpod-io/workspace-images#505]
In august the default tool that vscode-go used to debug running go apps changed from dlv to dlv-dap. You can see the documentation update here. https://github.com/golang/vscode-go/commit/a6066b73761fab8a8206786cc51734e92b5b4da3?short_path=cd5ab03

This requires an additional app to be installed in the full image or you will be prompted to install analysis tools on every workstation. https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile#L88

You can read more about installing dlv-dap here https://github.com/golang/vscode-go/blob/master/docs/debugging.md#manually-installing-dlv-dap

A workaround is to re-enable legacy mode in your launch.json: https://github.com/trashhalo/reddit-rss/commit/28693bfb3642a9f61551a78daf775119fdf79bc0#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945R12

**Comment by mattwelke** [comment]
A workaround I've been using for this is to add a step to my `init` task to manually set up delve for dlv-dap. I describe it in https://community.gitpod.io/t/how-do-i-set-up-dlv-dap-in-go-to-run-from-a-new-workspace/5669/2.

Another workaround if you don't want to tweak your `init` task is to just accept that when you launch your workspace, you'll need to invoke the debugger and then click "Install" or "Install All" in that interactive VS Code prompt to finish the workspace setup, as I described in https://github.com/go-delve/delve/issues/2808.

**Comment by kylos101** [comment]
Very helpful, [thanks for the heads up,](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#manually-installing-dlv) @mattwelke , I've scheduled this work accordingly.

**Comment by princerachit** [comment]
Hi @trashhalo and @mattwelke , is this still relevant with newer releases? Maybe this is already fixed. When I run a local test I can see that VS code is using `dap` keyword by default and I am not being prompted to install any tool.

Please correct me if my understanding of the issue is wrong.

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/32481722/156718546-5e44274e-9005-41c8-9e3c-0229678f2a85.png">

I also see that the dlv version is 1.8.2 which was released recently.
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/32481722/156718617-495e46c7-5f76-42b0-a565-e11e330b8377.png">

Also the dlv help says that you can use the `dap` keyword with it 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/32481722/156718928-bd53469b-b5db-4c86-ad6f-0e621a7925b9.png">

**Comment by princerachit** [comment]
Sorry for the incorrect version. I have updated the comment and screenshot @kylos101 .

**Comment by kylos101** [comment]
Hey @princerachit , I agree that debug works when using extension [golang.go](https://github.com/gitpod-io/template-golang-cli/blob/12ffbca961bbc13b598dcf694866987888e29ac6/.gitpod.yml#L10). For example, [using this repo as a test](gitpod.io/#https://github.com/gitpod-io/template-golang-cli), when I use the default `launch.json` config:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}"
        }
    ]
}
```

Then I am able to set breakpoints, and hit them when I start debug:
![image](https://user-images.githubusercontent.com/1272076/157319660-4dcc67ef-193b-471e-9802-a1e1754346e9.png)

However, I wonder if @trashhalo or @mattwelke are talking about this?
![image](https://user-images.githubusercontent.com/1272076/157309107-097eeb25-46ce-46d3-9a0b-bf544996d4ef.png)

When I click show to see which tools are missing, it indicates `staticcheck` is missing:
![image](https://user-images.githubusercontent.com/1272076/157319776-bb5468da-5e36-4d5d-bada-a5ad7f53ade1.png)

Regardless, because it is unclear, I am going to add this to our blocked list for now. 

@trashhalo @mattwelke are you able to reproduce the trouble that you're having using this [repo](https://github.com/gitpod-io/template-golang-cli)? If yes, may I ask you to share how?

**Comment by mattwelke** [comment]
@kylos101 That repo worked out of the box for me. I was able to run the debugger without being prompted to install any Go tools. I'd say it's resolved.

**Comment by mattwelke** [comment]
> However, I wonder if @trashhalo or @mattwelke[](https://user-images.githubusercontent.com/1272076/157309107-097eeb25-46ce-46d3-9a0b-bf544996d4ef.png) are talking about this?
image

One more thing. No, this wasn't the issue I was facing. It was that in a brand new Go project in GitPod, it lacked the tool needed to run the Go debugger.
