### ISSUE TITLE
Bump PHP to v8

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/workspace-images#545]
https://twitter.com/MrXenTV/status/1453401792172154882

**Comment by apolopena** [comment]
FYI Laravel 8 does not require PHP 8. 
At the time of writing this, PHP 8 is only 15% adopted right now while php 7.4 still has the highest adoption rate at 46%. This change has broken alot of my projects that I will need to fix. Also forcing everyone one to use a PHP version that not yet adopted well doesn't seem necessary. Sorry to comment on a closed issue. I just wanted to voice my thoughts regarding this important upgrade and since the change is already made it seems that there is no point to opening another issue for this since it would not make sense to roll back  this image to PHP 7.4.
Maybe in the future it would be good to consider taking more input from users before making an major PHP upgrade in the full image like this?
