### ISSUE TITLE
Why isn't .NET in the full image?

### ISSUE THREAD

**Issue by jchannon** [gitpod-io/workspace-images#556]
As the title suggests, we have Go, Java, Rust but no .NET. Any reason why?

**Comment by MedzikUser** [comment]
why not 😅

**Comment by ghuntley** [comment]
No reason why. Send in the pull request. I'd like to retire the majority of images under maintenance and move towards more things in full. An RFC is being authored rn by myself.

**Comment by kylos101** [comment]
Hi @jchannon :wave: ,

It is currently intentional for us to not include dotnet in the full image. Adding more to the full image (given our current design) will slow many workspace starts. `workspace-full` is used as our default image and also by folks as a base image for their custom dockerfile. 

The dotnet layer is about 500MB, which would equate to 5-10 seconds of additional pull time on our nodes (especially if we invalidate the cache on disk). 

Please continue using `gitpod/workspace-dotnet` for now as a base? If may also [create a custom image which you maintain yourself](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile), using `gitpod/workspace-dotnet` as the base.

We're constantly working on improving workspace start times, and plan to:
1. Improve distribution (decreasing start time)
2. Support lazy loading (decreasing the time till a workspace is usable)
3. Let users specify "chunks" for their image (like dotnet), without having to rely on a base image like workspace-dotnet

I am going to close this for now. If you feel strongly that this should be reopened, or have any questions, let us know?
