### ISSUE TITLE
[VNC] integrate minimal window manager

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#56]
Right now, via VNC it's possible to render an application window. 

However, it's hard to use because the application is by default a small window in the middle of the screen and I can't maximise, move or resize the window. 

Maybe we can integrate a minimalist window manager so that application windows can be resized and moved. Maybe maximised. It should be minimalistic to to eat as less RAM as possible.

**Comment by meysholdt** [comment]
A great repo to reproduce this: https://github.com/ssloy/tinyraycaster

**Comment by jankeromnes** [comment]
Good idea. FYI we use Fluxbox in Janitor's noVNC, which allows maximizing windows (I think Fluxbox suggested by noVNC, because it's lightweight).

But maybe we'd want something like a tiling window manager (e.g. Awesome), to make the best of available screen space? Also, it'd be really nice to have the Xvfb screen size match noVNC's iframe, so that you don't have to pan around to find your UI (especially with the in-IDE preview pane).
