### ISSUE TITLE
Use main, instead of master, for default branch

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#643]
The default branch in workspace-images is currently master.

[Let's change to main.](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main)

**Comment by princerachit** [comment]
I used the [branch renaming feature](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) of github instead of creating a new branch from CLI. This gives us added advantage of PR base branch update and other changes.

**Comment by princerachit** [comment]
I have made the changes and will monitor it for a day before closing this issue.
