### ISSUE TITLE
workspace-full — Include common Cloud Service Provider CLIs eg. AWS, Azure, GCP

### ISSUE THREAD

**Issue by omenking** [gitpod-io/workspace-images#680]
It would be great if the workspace-full base image container the AWS, GCloud and Azure CLI.

It would also be great if within your Gitpod account you could set the default image to launch for workspaces with no .gitpod.yml specifying an image.

**Comment by princerachit** [comment]
Hi @omenking due to existence of multiple clis which are used by developers it is hard to accept such request. We want to keep the full image minimal (due to user dependencies we are not able to do it properly yet). So we encourage users to extend the full image using .gitpod.Dockerfile if they have specific needs.

About the second request I have created this issue https://github.com/gitpod-io/gitpod/issues/8184

**Comment by omenking** [comment]
If you cannot add them to the full image then create a new workspaces/cloud image that extends full and support that.
