### ISSUE TITLE
yugabytedb dedicated workspace-images (base image)

### ISSUE THREAD

**Issue by srinivasa-vasu** [gitpod-io/workspace-images#737]
We are working towards providing an integrated developer experience for the Yugabyte community. We want to contribute a dedicated base image for [YugabyteDB](https://www.yugabyte.com/yugabytedb/) to have a better language runtime integrated experience. 

We have this integration published in the [Docs site](https://docs.yugabyte.com/latest/develop/gitdev/gitpod/) based on `workspace-full` image. The intent of this issue is to improve it with a dedicated YugabyteDB image.

FYI = > https://github.com/gitpod-io/workspace-images/pull/604

**Comment by kylos101** [comment]
Hi @srinivasa-vasu :wave:, that would be great, thanks a lot for reaching out :pray: ! It looks like [this blog post](https://blog.yugabyte.com/better-developer-experience-yugabytedb-gitpod/) links to #604, therefore, I'll go ahead and reopen.

May I ask for your help to update #604?
1. Rebase your branch on our default (master) branch
2. Make changes in #604 to support dazzle v2
   * You can refer to the [mysql chunk](https://github.com/gitpod-io/workspace-images/blob/master/chunks/tool-mysql/Dockerfile) and [related tests](https://github.com/gitpod-io/workspace-images/blob/master/tests/tool-mysql.yaml) as a reference
   * As you can see here, there is a [new configuration file](https://github.com/gitpod-io/workspace-images/blob/fb61836cd6673a54861de621d41154a781b530c6/dazzle.yaml#L85-L89), please add a related entry
   * There are a couple spots in our CI that need to have yugabyte added [[1](https://github.com/gitpod-io/workspace-images/blob/fb61836cd6673a54861de621d41154a781b530c6/.github/promote-images.yml#L21)][[2](https://github.com/gitpod-io/workspace-images/blob/fb61836cd6673a54861de621d41154a781b530c6/.github/sync-containers.yml#L18)]
3. Our [contribution guide](https://github.com/gitpod-io/workspace-images/blob/master/CONTRIBUTING.md) mentions these things, but I tried to summarize (above).

As a heads up, our CI will run tests when you push code, but it takes ~1 hour because it tests everything. We're looking to [improve that experience](https://github.com/gitpod-io/dazzle/issues/38#issuecomment-1059256719) from within a Gitpod workspace via `dazzle-up.sh` (which currently takes ~1h, but we think we can reduce to ~5m, ideally later this week).
