### ISSUE TITLE
Consider pre-installing `hub`

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#77]
https://github.com/github/hub

And make sure it is authenticated in Gitpod.

**Comment by jankeromnes** [comment]
FYI that's what we use in Janitor to allow users to pull/push/fork with GitHub.

We configure it by adding a GitHub token in `~/.netrc` and `~/.config/hub` [like so](https://github.com/JanitorTechnology/janitor/commit/be78b4dbd9696c5ac2f1e7c818314c22e5f84738), but for Gitpod it would be great to use the Git credential helper instead, because that's much safer.

**Comment by jankeromnes** [comment]
Tracked as part of #76.
