### ISSUE TITLE
Make available base + minimum set of tools (no lang) image 

### ISSUE THREAD

**Issue by mruzekw** [gitpod-io/workspace-images#792]
I'm just playing around with custom docker images on gitpod and noticed that only the `gitpod/workspace-full` image provides tools like homebrew and nix.

The image is HUGE and takes a while to build.

It would be great to have an image without any lang runtimes so that we can just install what we'd like with homebrew or nix and have a lean(er) image to start with.

I'm just thinking something like base (dep-cacert-update, tool-docker, tool-tailscale) +

tool-brew
tool-chrome
tool-nix
tool-vnc

**Comment by kylos101** [comment]
Hey @mruzekw , have you tried `workspace-base` as a base? I assume yes, because you references [its few chunks](https://github.com/gitpod-io/workspace-images/blob/8a4fcd02e7c09389af5e5e3e7860e3d69d82474a/dazzle.yaml#L3-L7). To recap, you can then [layer on your own changes in a dockerfile that you manage](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile:~:text=If%20you%20want%20a%20base%20image%20without%20the%20default%20tooling%20installed%20then%20use%20the%20gitpod/workspace%2Dbase%20image.).

Different people have different definitions of what it means to have a base image. Some might want Firefox, instead of Chrome, and not want Nix or VNC.

For the meantime, `workspace-base` is what you're looking for. For the long term, we'd look to rewrite our image builder, so that users can dynamically specify the chunks that they desire (and they would be lazy loaded on workspace start).

**Comment by kylos101** [comment]
👋 @mruzekw I am going to close this issue for now, please let me know if you'd like me to reopen, and if so, how else we might be able to help you? 🙏
